version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
<<<<<<< HEAD
      MYSQL_ROOT_PASSWORD:
=======
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
>>>>>>> 3997eb0 (try)
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    image: tp-foyer:latest
    build: ./
    depends_on:
      - mysqldb
    restart: always
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db:
